Select * from Hry
Insert INTO Hry Values
(1,'Counter Strike: GO'),
(2,'Dota2'),
(3,'hearthstone');


SELECT * FROM Lokace
INSERT INTO Lokace Values 
(1,'USA','Kalifornie','Anaheim')


Select * from Liga
Insert INTO Liga Values
(1,1,1,'ECS Season 2 Finals',8,'$750,000','9.12.2016','11.12.2016')


Select * From Tymy
Insert INTO Tymy Values
(1,1,1,'SK Gaming','Brazil')
Select * from Statistiky_Tymu
INSERT INTO Statistiky_Tymu Values
(1,'5','-','-','-','2','$857,242','160','128','6')

Alter TABLE Hraci ADD Nick CHAR(50)

Select * From Hraci
INSERT INTO Hraci Values
(1,'Gabriel','Toledo','Brazil',25,1,'FalleN'),
(2,'Fernando','Alvarenga','Brazil',25,1,'Fer'),
(3,'Marcelo','David','Brazil',22,1,'Coldzera'),
(4,'Epitacio','de Melo','Brazil',21,1,'Taco'),
(5,'Ricardo','Pacheco','Portugal',30,1,'Fox')

SELECT * from Tymy t 
JOIN Liga l ON l.lID=t.tID
JOIN Hry g ON g.gID=l.gID



/*Vytvoreni*/
-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2016-12-10 17:13:25 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012




CREATE
  TABLE Hraci
  (
    pID       INTEGER NOT NULL ,
    Jmeno     CHAR (50) NOT NULL ,
    Prijmeni  CHAR (50) NOT NULL ,
    Narodnost CHAR (30) NOT NULL ,
    Vek       INTEGER NOT NULL ,
    Tymy_tID  INTEGER
  )
  ON "default"
GO
ALTER TABLE Hraci ADD CONSTRAINT Hraci_PK PRIMARY KEY CLUSTERED (pID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Hry
  (
    gID       INTEGER NOT NULL ,
    Jmeno_hry CHAR (50) NOT NULL
  )
  ON "default"
GO
ALTER TABLE Hry ADD CONSTRAINT Hry_PK PRIMARY KEY CLUSTERED (gID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Liga
  (
    lID        INTEGER NOT NULL ,
    gID        INTEGER ,
    lokID      INTEGER ,
    Nazev_ligy CHAR (50) NOT NULL ,
    Poc_tymu   INTEGER ,
    Prize_pool CHAR (120) NOT NULL ,
    Zacatek    CHAR (50) NOT NULL ,
    Konec      CHAR (50) NOT NULL
  )
  ON "default"
GO
ALTER TABLE Liga ADD CONSTRAINT Liga_PK PRIMARY KEY CLUSTERED (lID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Lokace
  (
    lokID     INTEGER NOT NULL ,
    Kontinent CHAR (50) NOT NULL ,
    Stat      CHAR (50) NOT NULL ,
    Mesto     CHAR (50) NOT NULL
  )
  ON "default"
GO
ALTER TABLE Lokace ADD CONSTRAINT Lokace_PK PRIMARY KEY CLUSTERED (lokID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Statistiky_Tymu
  (
    stID             INTEGER NOT NULL ,
    Global           INTEGER ,
    EU_West          INTEGER ,
    EU_East          INTEGER ,
    Asia_and_Oceania INTEGER ,
    America          INTEGER ,
    Win_money        CHAR (120) NOT NULL ,
    Vyhry            INTEGER ,
    Prohry           INTEGER ,
    Remizy           INTEGER
  )
  ON "default"
GO
ALTER TABLE Statistiky_Tymu ADD CONSTRAINT Statistiky_Tymu_PK PRIMARY KEY
CLUSTERED (stID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Tymy
  (
    tID        INTEGER NOT NULL ,
    lID        INTEGER NOT NULL ,
    stID       INTEGER NOT NULL ,
    Nazev_tymu CHAR (30) NOT NULL ,
    Narodnost  CHAR (30) NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Tymy__IDX ON Tymy
(
  stID
)
ON "default"
GO
ALTER TABLE Tymy ADD CONSTRAINT Tymy_PK PRIMARY KEY CLUSTERED (tID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

ALTER TABLE Hraci
ADD CONSTRAINT Hraci_Tymy_FK FOREIGN KEY
(
Tymy_tID
)
REFERENCES Tymy
(
tID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Liga
ADD CONSTRAINT Liga_Hry_FK FOREIGN KEY
(
gID
)
REFERENCES Hry
(
gID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Liga
ADD CONSTRAINT Liga_Lokace_FK FOREIGN KEY
(
lokID
)
REFERENCES Lokace
(
lokID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Tymy
ADD CONSTRAINT Tymy_Liga_FK FOREIGN KEY
(
lID
)
REFERENCES Liga
(
lID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Tymy
ADD CONSTRAINT Tymy_Statistiky_Tymu_FK FOREIGN KEY
(
stID
)
REFERENCES Statistiky_Tymu
(
stID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
